# Generated by Django 2.1.2 on 2018-12-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0003_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num_joined',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='num_players',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        # migrations.AddField(
        #     model_name='game',
        #     name='num_spectators',
        #     field=models.IntegerField(default=0),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='game',
            name='num_teams',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='score_to_play_to',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
